@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

WhoDat *-right-> "1" UniquePersonList
WhoDat *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *-right-> "1" Name
Person *-right-> "1" StudentId
Person *-right-> "1" EmailId
Person *-right-> "1" ClassId
@enduml
