@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedWhoDat" as VersionedWhoDat MODEL_COLOR
end box

[-> Model : undoWhoDat()
activate Model

Model -> VersionedWhoDat : undo()
activate VersionedWhoDat

VersionedWhoDat -> VersionedWhoDat :resetData(ReadOnlyWhoDat)
VersionedWhoDat --> Model :
deactivate VersionedWhoDat

[<-- Model
deactivate Model

@enduml
