@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WhoDatParser" as WhoDatParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> WhoDatParser : parseCommand(undo)
activate WhoDatParser

create UndoCommand
WhoDatParser -> UndoCommand
activate UndoCommand

UndoCommand --> WhoDatParser
deactivate UndoCommand

WhoDatParser --> LogicManager : u
deactivate WhoDatParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoWhoDat()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
